FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Install nodemon globally
RUN npm install -g nodemon

# Copy application code
COPY . .

# Make the entrypoint script executable
RUN chmod +x docker-entrypoint.sh

EXPOSE 3000

# Set the entrypoint script
ENTRYPOINT ["/app/docker-entrypoint.sh"]

# Run the default command
CMD ["npm", "run", "dev"] 