version: '3'

services:
  jetson-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    privileged: true  # Cần quyền privileged để truy cập camera
    volumes:
      - ./data:/app/data  # Chia sẻ thư mục dữ liệu
      - /tmp/.X11-unix:/tmp/.X11-unix  # Cho hiển thị đồ họa (nếu cần)
    environment:
      - DISPLAY=${DISPLAY}  # Cho hiển thị đồ họa (nếu cần)
      - SERVER_URL=http://web-service:8000
      - CAMERA_ID=0
      - LOG_LEVEL=INFO
    devices:
      - /dev/video0:/dev/video0  # Truy cập camera
    networks:
      - fams-network

networks:
  fams-network:
    driver: bridge 