# Model paths
weights:
  dir: "assets/weights"
  detection: "retinaface.onnx"
  recognition: "adaface.onnx"

# Database paths
data:
  gallery: "data/gallery"
  database: "assets/database"

# Model parameters
detection:
  input_size: [640, 640]
  threshold: 0.5

recognition:
  threshold: 0.4
  embedding_dim: 512

# Face Anti-spoofing parameters
anti_spoofing:
  var_thresh: 5000.0
  grad_thresh: 0.7
  depth_range_thresh: 30.0
  min_depth_thresh: 50.0
  max_depth_thresh: 200.0
  normalize_method: "min_max"