FROM node:20-alpine

WORKDIR /app

# Copy package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install
# Install TypeScript globally
RUN npm install -g typescript

# Copy the rest of the application
COPY . .

# Set environment variables
ENV REACT_APP_API_URL=http://localhost:3000/api
ENV NODE_ENV=development
ENV WDS_SOCKET_PORT=0

EXPOSE 3000

CMD ["npm", "start"] 