services:
  backend-nodejs:
    build:
      context: ./backend/NodeJS-services
      dockerfile: Dockerfile.dev
    container_name: fams_backend_nodejs
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./backend/NodeJS-services:/app
      - /app/node_modules
    env_file:
      - ./backend/NodeJS-services/.env
    environment:
      - PORT=3000
    networks:
      - app-network

  backend-python:
    build:
      context: ./backend/Python-services
      dockerfile: Dockerfile.dev
    container_name: fams_backend_python
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./backend/Python-services:/app
      - /app/data
    env_file:
      - ./backend/Python-services/.env
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - IS_DOCKER=true
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: fams_frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3000/api
    depends_on:
      - backend-nodejs
      - backend-python
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: 